version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - auth-service
      - storage-service
      - data-service

  # Остальные сервисы (пример для auth-service)
  auth-service:
    build: ./backend/auth-service
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=postgres-auth
      - DB_PORT=5432
    depends_on:
      - postgres-auth

  postgres-auth:
    image: postgres:13
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    volumes:
      - auth-data:/var/lib/postgresql/data

  # Аналогично для других сервисов...

volumes:
  auth-data:
  mongo-data:
  minio-data:
